insert into product (id, name, price) values (4, 'Apple', 1);
insert into product (id, name, price) values (5, 'Apple', 2);
insert into product (id, name, price) values (3, 'Apple', 3);
insert into product (id, name, price) values (6, 'Apple', 4);
insert into product (id, name, price) values (7, 'Apple', 5);
insert into product (id, name, price) values (8, 'Apple', 6);
insert into product (id, name, price) values (9, 'Apple', 7);
insert into product (id, name, price) values (10, 'Apple',8);
insert into product (id, name, price) values (11, 'Apple',9);
insert into product (id, name, price) values (12, 'Apple',10);
insert into product (id, name, price) values (13, 'Apple',11);
insert into product (id, name, price) values (14, 'Apple',12);
insert into product (id, name, price) values (15, 'Apple',13);
insert into product (id, name, price) values (16, 'Apple',14);
insert into product (id, name, price) values (17, 'Apple',15);
insert into product (id, name, price) values (18, 'Apple',16);
insert into product (id, name, price) values (19, 'Apple',17);
insert into product (id, name, price) values (20, 'Apple',18);
insert into product (id, name, price) values (21, 'Apple',19);
insert into product (id, name, price) values (22, 'Apple',20);
insert into product (id, name, price) values (23, 'Apple',21);
insert into product (id, name, price) values (24, 'Apple',22);
insert into product (id, name, price) values (25, 'Apple',23);
insert into product (id, name, price) values (26, 'Apple',24);
insert into product (id, name, price) values (27, 'Apple',25);
insert into product (id, name, price) values (28, 'Apple',26);
insert into product (id, name, price) values (29, 'Apple',27);
insert into product (id, name, price) values (30, 'Apple',28);
insert into product (id, name, price) values (31, 'Apple',29);
insert into product (id, name, price) values (32, 'Apple',30);
